name: demo
channels:
  - defaults
dependencies:
  - python=3.6
  - jupyter
  - jupyterlab
  - numpy=1.14.3
  - matplotlib=3.0.2
  - pandas=0.22.0
  - scikit-learn=0.19.1
  - pip:
    - mlflow
    - papermill
